name: Build and deploy

on:
  push:
    tags: v[1-9]+.[0-9]+.[0-9]+

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup PNPM
        uses: pnpm/setup@v2
        with:
          version: 11

      - name: Actions/setup-node
        uses: actions/setup-node@v7
        with:
          node-version: '26.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create env file
        run: |
          touch .env
          echo VITE_LASTFM_APIKEY=${{ secrets.LASTFM_APIKEY }} >> .env
          echo VITE_LASTFM_SECRET=${{ secrets.LASTFM_SECRET }} >> .env
          echo VITE_FANART_APIKEY=${{ secrets.FANART_APIKEY }} >> .env

      - name: Build
        run: pnpm build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v4.0
        with:
          publish-dir: './dist'
          production-branch: main
          production-deploy: true
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
