name: Build

on:
  push:
    branches: ['feature/*']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Actions/setup-node
        uses: actions/setup-node@v7
        with:
          cache: 'pnpm'
          node-version: '26.x'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create env file
        run: |
          touch .env
          echo VITE_LASTFM_APIKEY=${{ secrets.LASTFM_APIKEY }} >> .env
          echo VITE_LASTFM_SECRET=${{ secrets.LASTFM_SECRET }} >> .env
          echo VITE_FANART_APIKEY=${{ secrets.FANART_APIKEY }} >> .env

      - name: Build
        run: pnpm build
